GarageV.Parrot/src/Entity/Schedule.php
<?php

namespace App\Entity;

use App\Repository\ScheduleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ScheduleRepository::class)]
class Schedule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $day = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $openAM = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $closeAM = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $openPM = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $closePM = null;

    #[ORM\Column]
    private ?bool $Active = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDay(): ?string
    {
        return $this->day;
    }

    public function setDay(string $day): static
    {
        $this->day = $day;

        return $this;
    }

    public function getOpenAM(): ?\DateTimeInterface
    {
        return $this->openAM;
    }

    public function setOpenAM(\DateTimeInterface $openAM): static
    {
        $this->openAM = $openAM;

        return $this;
    }

    public function getCloseAM(): ?\DateTimeInterface
    {
        return $this->closeAM;
    }

    public function setCloseAM(\DateTimeInterface $closeAM): static
    {
        $this->closeAM = $closeAM;

        return $this;
    }

    public function getOpenPM(): ?\DateTimeInterface
    {
        return $this->openPM;
    }

    public function setOpenPM(\DateTimeInterface $openPM): static
    {
        $this->openPM = $openPM;

        return $this;
    }

    public function getClosePM(): ?\DateTimeInterface
    {
        return $this->closePM;
    }

    public function setClosePM(\DateTimeInterface $closePM): static
    {
        $this->closePM = $closePM;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->Active;
    }

    public function setActive(bool $Active): static
    {
        $this->Active = $Active;

        return $this;
    }
}

GarageV.Parrot/templates/view/_delete_form.html.twig
<form method="post" action="{{ path('app_view_delete', {'id': view.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ view.id) }}">
    <button class="avis-affichage__btn__supprimer">Supprimer</button>
</form>

GarageV.Parrot/templates/view/_form.html.twig
{{ form_start(formulaireAvis, {'attr': {'class': 'formulaire-avis'}}) }}
    <div class="formulaire-avis__content">
        {% if app.request.attributes.get('_route') != 'app_view_edit' %}
            <img class="formulaire-avis__close-icon" src="{{ asset('dossier-image/nav/x-circle.svg') }}">
        {% endif %}
        <div class="formulaire-avis__name">
            {{ form_row(formulaireAvis.name) }}
        </div>
        <div class="formulaire-avis__firstName">
            {{ form_row(formulaireAvis.firstName) }}
        </div>
        <div class="formulaire-avis__comment">
            {{ form_row(formulaireAvis.comment) }}
        </div>
        <div class="formulaire-avis__score">
            {{ form_row(formulaireAvis.score) }}
        </div>
        <div class="formulaire-avis__active">
            {{ form_row(formulaireAvis.active) }}
        </div>
        {# Vérifier si la route est "view_edit" on affiche les images #}
        {% if app.request.attributes.get('_route') == 'app_view_edit' %}
        
        {% else %}
        {% endif %}
        <button class="btn-avis-valide">{{ button_label|default('ENVOYER') }}</button>
    </div>
{{ form_end(formulaireAvis) }}

GarageV.Parrot/templates/view/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Avis{% endblock %}

{% block body %}
    <h1>Modifier Avis</h1>

    {{ include('view/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_view_index') }}">back to list</a>

    {{ include('view/_delete_form.html.twig') }}
{% endblock %}

GarageV.Parrot/templates/view/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/view/view.css') }}">
{% endblock %}

{% block title %}Avis{% endblock %}

{% block body %}
    <header>
        <h1>Avis</h1>
        <a class="ajouter" href="{{ path('app_view_new') }}">Ajouter</a>
    </header>
    <main>
        {% for view in views %}
            <div class="avis-affichage">
                <div class="avis-affichage__name">
                    <p class="avis-affichage__name-description">Nom</p>
                    <p>{{ view.name }}</p>
                </div>
                <div class="avis-affichage__firstName">
                    <p class="avis-affichage__firstName-description">Prénom</p>
                    <p>{{ view.firstName }}</p>
                </div>
                <div class="avis-affichage__score">
                    <p class="avis-affichage__score-description">Note</p>
                    <p>{{ view.score }}/5</p>
                </div>
                <div class="avis-affichage__comment">
                    <p>Commentaire</p>
                    <p>{{ view.comment }}</p>
                </div>
                <div class="avis-affichage__btn">
                    {% if view.active == 1 %}
                    <p class="avis-affichage__btn__valider">Valider</p>
                    {% else %}
                    <p class="avis-affichage__btn__non-valider">Valider</p>
                    {% endif  %}
                    {{ include('view/_delete_form.html.twig') }}
                </div>
            </div>
        {% else %}
            <div>
                <h2>Aucun avis</h2>
            </div>
        {% endfor %}
    </main>
    <footer class='pagination'>
        {% for page in 1..totalPages %}
            {% if page == currentPage %}
                <span>{{ page }}</span>
            {% else %}
                <a class="page-non-courante" href="{{ path('app_view_index', {'page': page}) }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
    </footer>
{% endblock %}

GarageV.Parrot/templates/view/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Avis{% endblock %}

{% block body %}
    <h1>Nouvelle Avis</h1>

    {{ include('view/_form.html.twig') }}

    <a href="{{ path('app_view_index') }}">back to list</a>
{% endblock %}

GarageV.Parrot/templates/view/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}View{% endblock %}

{% block body %}
    <h1>View</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ view.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ view.name }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ view.firstName }}</td>
            </tr>
            <tr>
                <th>Comment</th>
                <td>{{ view.comment }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ view.score }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_view_index') }}">back to list</a>

    <a href="{{ path('app_view_edit', {'id': view.id}) }}">edit</a>

    {{ include('view/_delete_form.html.twig') }}
{% endblock %}